import { useEffect, useState } from 'react';
import { getReportHistory } from '../../../api/reportApi';
import {
  PageHeader, ReportCard, ReportTable, TableHead,
  LoadingState, EmptyState, ErrorState, Pagination,
} from '../../../components/reports';

const REPORT_TYPE_LABELS = {
  DATASET_REPORT: 'Dataset Report',
  MONTHLY_REPORT: 'Monthly Report',
  INDICATOR_REPORT: 'Indicator Report',
  SUBMISSION_STATUS_REPORT: 'Submission Status',
  CUSTOM_REPORT: 'Custom Report',
};

const REPORT_TYPE_COLOURS = {
  DATASET_REPORT: 'bg-blue-100 text-blue-800',
  MONTHLY_REPORT: 'bg-teal-100 text-teal-800',
  INDICATOR_REPORT: 'bg-purple-100 text-purple-800',
  SUBMISSION_STATUS_REPORT: 'bg-slate-100 text-slate-700',
  CUSTOM_REPORT: 'bg-amber-100 text-amber-800',
};

function formatDate(dt) {
  if (!dt) return '—';
  return new Date(dt).toLocaleDateString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

export default function ReportHistoryPage() {
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [page, setPage] = useState(1);

  async function load(p = page) {
    setLoading(true);
    setError('');
    try {
      const res = await getReportHistory({ page: p });
      setResult({ data: res.data, meta: res.meta });
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to load report history.');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(page); }, [page]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div>
      <PageHeader
        title="Report History"
        subtitle="A log of report requests you have generated."
      />

      {loading && <LoadingState message="Loading report history…" />}
      {error && <ErrorState message={error} onRetry={() => load(page)} />}

      {!loading && !error && result && (
        <ReportCard>
          {result.data.length === 0 ? (
            <EmptyState
             
              title="No report history yet"
              message="Report history will appear here after you generate reports."
            />
          ) : (
            <>
              <ReportTable>
                <TableHead cols={[
                  { label: 'Report Type' },
                  { label: 'Dataset' },
                  { label: 'Period' },
                  { label: 'Indicator' },
                  { label: 'Generated By' },
                  { label: 'Accessed At', right: true },
                ]} />
                <tbody>
                  {result.data.map(h => {
                    let params = null;
                    try { params = h.parameters ? JSON.parse(h.parameters) : null; } catch { params = null; }
                    const isCustom = h.report_type === 'CUSTOM_REPORT';
                    return (
                    <tr key={h.id} className="border-t border-slate-100 hover:bg-slate-50 transition-colors">
                      <td className="px-4 py-3">
                        <span className={`inline-block rounded-full px-2.5 py-0.5 text-xs font-semibold ${REPORT_TYPE_COLOURS[h.report_type] || 'bg-slate-100 text-slate-700'}`}>
                          {REPORT_TYPE_LABELS[h.report_type] || h.report_type}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-slate-600 text-sm">{h.dataset_name || '—'}</td>
                      <td className="px-4 py-3 text-slate-600 text-sm">
                        {isCustom && params?.period_labels?.length
                          ? params.period_labels.join(', ')
                          : (h.period_label || '—')}
                      </td>
                      <td className="px-4 py-3 text-slate-600 text-sm">
                        {isCustom && params?.indicator_names?.length
                          ? params.indicator_names.join(', ')
                          : (h.indicator_name || '—')}
                      </td>
                      <td className="px-4 py-3">
                        <p className="text-slate-700 text-sm">{h.user_name}</p>
                        <p className="text-slate-400 text-xs">{h.user_email}</p>
                      </td>
                      <td className="px-4 py-3 text-right text-slate-500 text-sm">{formatDate(h.accessed_at)}</td>
                    </tr>
                    );
                  })}
                </tbody>
              </ReportTable>
              <Pagination meta={result.meta} onPage={p => { setPage(p); load(p); }} />
            </>
          )}
        </ReportCard>
      )}
    </div>
  );
}

